# generated by datamodel-codegen:
#   filename:  genai-ny.json
#   timestamp: 2025-12-06T18:13:57+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class Coordinate(BaseModel):
    longitude: float
    latitude: float


class Calendar(BaseModel):
    access_level: str
    api_id: str
    avatar_url: str
    coordinate: Optional[Coordinate] = None
    cover_image_url: str
    description_short: str
    event_submission_restriction: str
    geo_city: str
    geo_country: str
    geo_region: str
    google_measurement_id: Optional[Any] = None
    instagram_handle: Optional[str] = None
    is_blocked: bool
    launch_status: str
    linkedin_handle: Optional[str] = None
    luma_plus_active: bool
    meta_pixel_id: Optional[Any] = None
    name: str
    personal_user_api_id: Optional[str] = None
    refund_policy: Optional[RefundPolicy] = None
    show_subscriber_count: bool
    slug: str
    social_image_url: str
    stripe_account_id: Optional[str] = None
    tax_config: Optional[Any] = None
    tiktok_handle: Optional[str] = None
    timezone: str
    tint_color: str
    track_meta_ads_from_luma: bool
    twitter_handle: Optional[str] = None
    verified_at: Optional[str] = None
    website: Optional[str] = None
    youtube_handle: Optional[str] = None
    is_personal: bool


class VirtualInfo(BaseModel):
    has_access: bool


class GeoAddressInfo(BaseModel):
    mode: Optional[str] = None
    city_state: Optional[str] = None
    sublocality: Optional[str] = None
    city: Optional[str] = None
    type: Optional[str] = None
    region: Optional[str] = None
    address: Optional[str] = None
    country: Optional[str] = None
    place_id: Optional[str] = None
    description: Optional[str] = None
    country_code: Optional[str] = None
    full_address: Optional[str] = None
    apple_maps_place_id: Optional[str] = None


class Coordinate1(BaseModel):
    latitude: float
    longitude: float


class Event(BaseModel):
    api_id: str
    calendar_api_id: str
    cover_url: str
    end_at: str
    event_type: str
    hide_rsvp: bool
    location_type: str
    name: str
    one_to_one: bool
    recurrence_id: Optional[Any] = None
    show_guest_list: bool
    start_at: str
    timezone: str
    url: str
    user_api_id: str
    visibility: str
    waitlist_enabled: bool
    virtual_info: VirtualInfo
    geo_address_info: Optional[GeoAddressInfo] = None
    geo_address_visibility: str
    coordinate: Optional[Coordinate1] = None


class CoverImage(BaseModel):
    vibrant_color: Optional[Any] = None
    colors: List[str]


class Coordinate2(BaseModel):
    longitude: float
    latitude: float


class Attrs(BaseModel):
    href: str


class Mark(BaseModel):
    type: str
    attrs: Attrs


class ContentItem1(BaseModel):
    text: Optional[str] = None
    type: Optional[str] = None
    marks: Optional[List[Mark]] = None


class ContentItem(BaseModel):
    type: Optional[str] = None
    content: Optional[List[ContentItem1]] = None


class RefundPolicy(BaseModel):
    type: str
    content: Optional[List[ContentItem]] = None


class Calendar1(BaseModel):
    access_level: str
    api_id: str
    avatar_url: Optional[str] = None
    coordinate: Optional[Coordinate2] = None
    cover_image_url: Optional[str] = None
    description_short: Optional[str] = None
    event_submission_restriction: str
    geo_city: Optional[str] = None
    geo_country: Optional[str] = None
    geo_region: Optional[str] = None
    google_measurement_id: Optional[Any] = None
    instagram_handle: Optional[str] = None
    is_blocked: bool
    launch_status: str
    linkedin_handle: Optional[str] = None
    luma_plus_active: bool
    meta_pixel_id: Optional[Any] = None
    name: str
    personal_user_api_id: Optional[str] = None
    refund_policy: Optional[RefundPolicy] = None
    show_subscriber_count: bool
    slug: Optional[str] = None
    social_image_url: Optional[str] = None
    stripe_account_id: Optional[str] = None
    tax_config: Optional[Any] = None
    tiktok_handle: Optional[str] = None
    timezone: Optional[str] = None
    tint_color: str
    track_meta_ads_from_luma: bool
    twitter_handle: Optional[str] = None
    verified_at: Optional[str] = None
    website: Optional[str] = None
    youtube_handle: Optional[str] = None
    is_personal: bool


class Host(BaseModel):
    name: str
    api_id: str
    website: Optional[str]
    timezone: str
    username: Optional[str]
    bio_short: Optional[str]
    avatar_url: str
    is_verified: bool
    tiktok_handle: None
    last_online_at: Optional[str]
    twitter_handle: Optional[str]
    youtube_handle: Optional[str]
    linkedin_handle: Optional[str]
    instagram_handle: Optional[str]


class Price(BaseModel):
    cents: int
    currency: str
    is_flexible: bool


class CurrencyInfo(BaseModel):
    currency: str
    decimals: int


class TicketInfo(BaseModel):
    price: Optional[Price]
    is_free: bool
    max_price: None
    is_sold_out: bool
    spots_remaining: Optional[int]
    is_near_capacity: bool
    require_approval: bool
    currency_info: Optional[CurrencyInfo]


class FeaturedGuest(BaseModel):
    api_id: str
    avatar_url: str
    bio_short: Optional[str]
    instagram_handle: Optional[str]
    is_verified: bool
    last_online_at: Optional[str]
    linkedin_handle: Optional[str]
    name: str
    tiktok_handle: Optional[str]
    timezone: str
    twitter_handle: Optional[str]
    username: Optional[str]
    website: Optional[str]
    youtube_handle: Optional[str]


class Tag(BaseModel):
    api_id: str
    name: str
    color: str


class FeaturedItem(BaseModel):
    api_id: str
    event: Event
    cover_image: CoverImage
    calendar: Calendar1
    start_at: str
    hosts: List[Host]
    guest_count: int
    ticket_count: int
    ticket_info: TicketInfo
    featured_guests: List[FeaturedGuest]
    role: Optional[Any] = None
    waitlist_active: bool
    calendar_api_id: str
    is_manager: bool
    platform: str
    status: str
    submitted_by_user_api_id: str
    tags: List[Tag]


class Tag1(BaseModel):
    api_id: str
    name: str
    color: str
    upcoming_event_count: int


class AccessInfo(BaseModel):
    type: str
    require_approval: bool
    currency: Optional[str] = None
    amount_yearly: Optional[int] = None
    amount_monthly: Optional[int] = None
    stripe_account_id: Optional[str] = None
    stripe_product_id: Optional[str] = None
    stripe_yearly_price_id: Optional[str] = None
    stripe_monthly_price_id: Optional[str] = None


class RegistrationQuestion(BaseModel):
    id: str
    label: str
    options: List[str]
    required: bool
    question_type: str
    job_title_label: Optional[str] = None
    collect_job_title: Optional[bool] = None


class MembershipTier(BaseModel):
    api_id: str
    access_info: AccessInfo
    description: str
    registration_questions: List[RegistrationQuestion]
    calendar_api_id: str
    tint_color: str
    name: str


class Model(BaseModel):
    calendar: Calendar
    featured_items: List[FeaturedItem]
    has_upcoming_events: bool
    has_access: bool
    is_admin: bool
    calendar_member: Optional[Any] = None
    is_subscriber: bool
    tags: List[Tag1]
    event_start_ats: List[str]
    membership_tiers: List[MembershipTier]
    subscriber_count: Optional[Any] = None
    categories: List[Any]
    membership_info: Optional[Any] = None
    can_subscribe: bool
